// Les sous-chapitres : des intertitres posés sur le verset où ils commencent (un sous-chapitre va jusqu'au
// suivant). Ni la base AELF ni aelf.org n'en ont : ceux-ci ont été proposés par Claude (2026-10-03), avec des
// titres courts et neutres, pour les chapitres des 32 épisodes, et validés par Marin (2026-10-06).
// status : 'proposé' (pas encore relu : jamais mis en ligne) ou 'validé' (relu par Marin : mis en ligne
//   au prochain npm run seed:prod). Un nouveau sous-chapitre proposé par Claude commence en 'proposé'.
// start = [chapitre, verset] en TEXTE comme dans la Bible AELF.
// Après une modification : npm run seed (il vérifie que chaque verset de début existe)

const validated = (book, chapter, verse, title) => ({ book, start: [chapter, verse], title, status: 'validé' });

export const sections = [
  // La Création (Gn 1 – 2)
  validated('Gn', '1', '1', 'La lumière'),
  validated('Gn', '1', '6', 'Le firmament'),
  validated('Gn', '1', '9', 'La terre et les plantes'),
  validated('Gn', '1', '14', 'Le soleil, la lune et les étoiles'),
  validated('Gn', '1', '20', 'Les poissons et les oiseaux'),
  validated('Gn', '1', '24', 'Les animaux et l\'homme'),
  validated('Gn', '2', '1', 'Le septième jour'),
  validated('Gn', '2', '4', 'Le jardin d\'Éden'),
  validated('Gn', '2', '18', 'La femme'),
  // La chute (Gn 3)
  validated('Gn', '3', '1', 'Le serpent'),
  validated('Gn', '3', '8', 'Où es-tu ?'),
  validated('Gn', '3', '14', 'Les conséquences'),
  validated('Gn', '3', '20', 'Hors du jardin'),
  // Noé (Gn 6 – 9)
  validated('Gn', '6', '1', 'La violence sur la terre'),
  validated('Gn', '6', '9', 'L\'arche'),
  validated('Gn', '7', '1', 'L\'entrée dans l\'arche'),
  validated('Gn', '7', '17', 'Les eaux montent'),
  validated('Gn', '8', '1', 'Les eaux baissent'),
  validated('Gn', '8', '15', 'La sortie de l\'arche'),
  validated('Gn', '8', '20', 'L\'offrande de Noé'),
  validated('Gn', '9', '1', 'La bénédiction de Noé'),
  validated('Gn', '9', '8', 'L\'alliance et l\'arc'),
  validated('Gn', '9', '18', 'Les fils de Noé'),
  // Abraham (Gn 12, 15, 22)
  validated('Gn', '12', '1', 'L\'appel et le départ'),
  validated('Gn', '12', '10', 'Abram en Égypte'),
  validated('Gn', '15', '1', 'Une descendance comme les étoiles'),
  validated('Gn', '15', '7', 'L\'alliance scellée'),
  validated('Gn', '22', '1', 'L\'épreuve'),
  validated('Gn', '22', '15', 'La bénédiction renouvelée'),
  validated('Gn', '22', '20', 'La famille de Nahor'),
  // Joseph (Gn 37, 45)
  validated('Gn', '37', '1', 'Les rêves de Joseph'),
  validated('Gn', '37', '12', 'Joseph vendu'),
  validated('Gn', '45', '1', 'Joseph se fait reconnaître'),
  validated('Gn', '45', '16', 'Le retour vers Jacob'),
  // L'Exode (Ex 3, 12, 14, 19 – 20)
  validated('Ex', '3', '1', 'Le buisson ardent'),
  validated('Ex', '3', '13', 'Le nom de Dieu'),
  validated('Ex', '3', '16', 'La mission auprès des anciens'),
  validated('Ex', '12', '1', 'Les rites de la Pâque'),
  validated('Ex', '12', '29', 'La nuit de la sortie'),
  validated('Ex', '12', '37', 'Le départ'),
  validated('Ex', '14', '1', 'Pharaon poursuit Israël'),
  validated('Ex', '14', '15', 'Le passage de la mer'),
  validated('Ex', '14', '26', 'Les eaux reviennent'),
  validated('Ex', '19', '1', 'Au pied du Sinaï'),
  validated('Ex', '19', '16', 'Dieu descend sur la montagne'),
  validated('Ex', '20', '1', 'Les dix paroles'),
  validated('Ex', '20', '18', 'La crainte du peuple'),
  validated('Ex', '20', '22', 'L\'autel'),
  // La Terre promise (Jos 3, 6)
  validated('Jos', '3', '1', 'Les préparatifs'),
  validated('Jos', '3', '14', 'Le Jourdain s\'arrête'),
  validated('Jos', '6', '1', 'Sept jours autour de Jéricho'),
  validated('Jos', '6', '15', 'La chute des remparts'),
  validated('Jos', '6', '22', 'Rahab épargnée'),
  // La royauté (1 S 8 – 10, 16 – 17 ; 2 S 7 ; 1 R 3, 8)
  validated('1S', '8', '1', 'Le peuple demande un roi'),
  validated('1S', '8', '10', 'Les droits du roi'),
  validated('1S', '9', '1', 'Saül cherche les ânesses'),
  validated('1S', '9', '15', 'La rencontre avec Samuel'),
  validated('1S', '10', '1', 'L\'onction de Saül'),
  validated('1S', '10', '17', 'Saül désigné roi'),
  validated('1S', '16', '1', 'L\'onction de David'),
  validated('1S', '16', '14', 'David auprès de Saül'),
  validated('1S', '17', '1', 'Le défi de Goliath'),
  validated('1S', '17', '12', 'David arrive au camp'),
  validated('1S', '17', '31', 'David devant Saül'),
  validated('1S', '17', '40', 'Le combat'),
  validated('1S', '17', '55', 'Qui est ce jeune homme ?'),
  validated('2S', '7', '1', 'Le projet de David'),
  validated('2S', '7', '4', 'La promesse faite à David'),
  validated('2S', '7', '18', 'La prière de David'),
  validated('1R', '3', '1', 'Le songe de Gabaon'),
  validated('1R', '3', '16', 'Le jugement de Salomon'),
  validated('1R', '8', '1', 'L\'arche dans le Temple'),
  validated('1R', '8', '14', 'Le discours de Salomon'),
  validated('1R', '8', '22', 'La prière de Salomon'),
  validated('1R', '8', '54', 'La bénédiction et les sacrifices'),
  // Les prophètes (1 R 17 – 19 ; Is 6, 52 – 53)
  validated('1R', '17', '1', 'Élie au torrent'),
  validated('1R', '17', '7', 'La veuve de Sarepta'),
  validated('1R', '17', '17', 'Le fils de la veuve'),
  validated('1R', '18', '1', 'Élie et Abdias'),
  validated('1R', '18', '20', 'Le sacrifice sur le Carmel'),
  validated('1R', '18', '41', 'La pluie revient'),
  validated('1R', '19', '1', 'La fuite d\'Élie'),
  validated('1R', '19', '9', 'À l\'Horeb'),
  validated('1R', '19', '19', 'L\'appel d\'Élisée'),
  validated('Is', '6', '1', 'La vision dans le Temple'),
  validated('Is', '6', '8', 'Qui enverrai-je ?'),
  validated('Is', '52', '13', 'Le Serviteur élevé'),
  validated('Is', '53', '1', 'Méprisé et rejeté'),
  validated('Is', '53', '10', 'La multitude justifiée'),
  // L'Exil et le retour (2 R 25 ; Jr 29 ; Esd 1)
  validated('2R', '25', '1', 'Le siège de Jérusalem'),
  validated('2R', '25', '8', 'Le Temple incendié'),
  validated('2R', '25', '22', 'Godolias'),
  validated('2R', '25', '27', 'Jékonias libéré'),
  validated('Jr', '29', '1', 'La lettre aux exilés'),
  validated('Jr', '29', '10', 'Un avenir et une espérance'),
  validated('Jr', '29', '15', 'Contre les faux prophètes'),
  validated('Esd', '1', '1', 'L\'édit de Cyrus'),
  validated('Esd', '1', '5', 'Les préparatifs du retour'),
  validated('Esd', '1', '7', 'Les objets du Temple'),
  // Jésus (Lc 1 – 2, 22 – 24 ; Mt 5 ; Jn 20)
  validated('Lc', '1', '1', 'Prologue'),
  validated('Lc', '1', '5', 'L\'annonce à Zacharie'),
  validated('Lc', '1', '26', 'L\'annonce à Marie'),
  validated('Lc', '1', '39', 'Marie chez Élisabeth'),
  validated('Lc', '1', '46', 'Le chant de Marie'),
  validated('Lc', '1', '57', 'La naissance de Jean'),
  validated('Lc', '1', '67', 'Le chant de Zacharie'),
  validated('Lc', '2', '1', 'La naissance de Jésus'),
  validated('Lc', '2', '8', 'Les bergers'),
  validated('Lc', '2', '22', 'La présentation au Temple'),
  validated('Lc', '2', '41', 'Jésus au Temple à douze ans'),
  validated('Mt', '5', '1', 'Heureux'),
  validated('Mt', '5', '13', 'Le sel et la lumière'),
  validated('Mt', '5', '17', 'La Loi accomplie'),
  validated('Mt', '5', '21', 'La colère'),
  validated('Mt', '5', '27', 'Le regard'),
  validated('Mt', '5', '31', 'Le mariage'),
  validated('Mt', '5', '33', 'La parole donnée'),
  validated('Mt', '5', '38', 'Tendre l\'autre joue'),
  validated('Mt', '5', '43', 'Aimer ses ennemis'),
  validated('Lc', '22', '1', 'Le complot'),
  validated('Lc', '22', '7', 'La préparation de la Pâque'),
  validated('Lc', '22', '14', 'Le dernier repas'),
  validated('Lc', '22', '24', 'Le plus grand'),
  validated('Lc', '22', '31', 'Pierre averti'),
  validated('Lc', '22', '39', 'Au mont des Oliviers'),
  validated('Lc', '22', '47', 'L\'arrestation'),
  validated('Lc', '22', '54', 'Le reniement de Pierre'),
  validated('Lc', '22', '63', 'Devant le Conseil'),
  validated('Lc', '23', '1', 'Devant Pilate'),
  validated('Lc', '23', '6', 'Devant Hérode'),
  validated('Lc', '23', '13', 'La condamnation'),
  validated('Lc', '23', '26', 'Le chemin du Calvaire'),
  validated('Lc', '23', '33', 'La crucifixion'),
  validated('Lc', '23', '44', 'La mort de Jésus'),
  validated('Lc', '23', '50', 'Au tombeau'),
  validated('Lc', '24', '1', 'Le tombeau vide'),
  validated('Lc', '24', '13', 'Les disciples d\'Emmaüs'),
  validated('Lc', '24', '36', 'Jésus apparaît aux Onze'),
  validated('Lc', '24', '50', 'L\'Ascension'),
  validated('Jn', '20', '1', 'Le tombeau vide'),
  validated('Jn', '20', '11', 'Marie Madeleine'),
  validated('Jn', '20', '19', 'Jésus apparaît aux disciples'),
  validated('Jn', '20', '24', 'Thomas'),
  validated('Jn', '20', '30', 'Pourquoi ce livre'),
  // L'Église et l'accomplissement (Ac 2 ; Ap 21)
  validated('Ac', '2', '1', 'La venue de l\'Esprit'),
  validated('Ac', '2', '14', 'Le discours de Pierre'),
  validated('Ac', '2', '37', 'Les premiers baptisés'),
  validated('Ac', '2', '42', 'La vie de la communauté'),
  validated('Ap', '21', '1', 'Un ciel nouveau et une terre nouvelle'),
  validated('Ap', '21', '9', 'La Jérusalem nouvelle'),
];
